name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar o GitHub Pages
        uses: actions/configure-pages@v5

      - name: Carregar arquivos estáticos
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."  # se o Lovable gerar os arquivos em "dist" ou "public", mude aqui

      - name: Implantar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
